---
abstract: 'Sereal based persistence for Perl data structures'
author:
  - 'Gelu Lupaş <gvl@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SerealX-Store
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  SerealX::Store:
    file: lib/SerealX/Store.pm
    version: 0.001
requires:
  Sereal: 2.0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ggl/SerealX-Store/issues
  homepage: https://github.com/ggl/SerealX-Store
  repository: https://github.com/ggl/SerealX-Store.git
version: 0.001
x_authority: cpan:GVL
